<a href="https://colab.research.google.com/github/bsshreesha/Python-SQL-Assignment/blob/main/Introduction_to_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy Tutorial

### Introduction
NumPy (Numerical Python) is a powerful library for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these data structures efficiently.

---

## Why Use NumPy?
- **Performance**: NumPy arrays are faster than Python lists for numerical computations.
- **Memory Efficiency**: NumPy arrays consume less memory than Python lists.
- **Convenience**: Built-in functions make mathematical operations simpler and more efficient.
- **Integration**: Works well with other scientific computing and machine learning libraries like SciPy, Pandas, and TensorFlow.

---

## NumPy Basics
### Importing NumPy
To use NumPy, you need to import it first:
```python
import numpy as np
```

# What is an Array?
An **array** is a data structure that stores multiple values in a single variable. Arrays can be one-dimensional (like a list) or multi-dimensional (like a table or matrix). Arrays allow for efficient storage and retrieval of numerical data.

NumPy arrays are the core data structure in NumPy.

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print("NumPy Array:", arr)

NumPy Array: [1 2 3 4 5]


### Creating Multi-dimensional Arrays

In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D NumPy Matrix:\n", matrix)


2D NumPy Matrix:
 [[1 2 3]
 [4 5 6]]


## Array Creation Functions
### `np.arange()` - Create sequences of numbers

In [ ]:
arange_array = np.arange(0, 12, 1)  # Even numbers from 0 to 8
print("\nArange Array:", arange_array)


Arange Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


### `np.linspace()` - Create evenly spaced numbers

In [ ]:
linspace_array = np.linspace(0, 10, 6)  # 5 equally spaced values from 0 to 10
print("\nLinspace Array:", linspace_array)


Linspace Array: [ 0.  2.  4.  6.  8. 10.]


### `np.zeros()` - Create an array of zeros

In [ ]:
zeros_array = np.zeros((2, 2))
print("\nZeros Array:\n", zeros_array)


Zeros Array:
 [[0. 0.]
 [0. 0.]]


### `np.ones()` - Create an array of ones

In [ ]:
ones_array = np.ones((4, 4))
print("\nOnes Array:\n", ones_array)


Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### `np.eye()` - Create an identity matrix

In [ ]:
identity_matrix = np.eye(4)
print("\nIdentity Matrix:\n", identity_matrix)


Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Basic Mathematical Operations

In [ ]:
array1 = np.array([[10, 20, 30],[1,2,3]])
array2 = np.array([[1, 2, 3],[2,4,6]])

sum_result = array1 + array2
print("\nSum:", sum_result)

product_result = array1 * array2
print("\nElement-wise Multiplication:", product_result)


Sum: [[11 22 33]
 [ 3  6  9]]

Element-wise Multiplication: [[10 40 90]
 [ 2  8 18]]


In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D NumPy Matrix:\n", matrix)


2D NumPy Matrix:
 [[1 2 3]
 [4 5 6]]


## Reshaping and Transposing
### Reshape an array

In [ ]:
reshaped_matrix = matrix.reshape(3, 2)
print("\nReshaped Matrix:\n", reshaped_matrix)


Reshaped Matrix:
 [[ 1  2]
 [ 3 11]
 [12 13]]


### Transpose an array

In [ ]:
transposed_matrix = matrix.T
print("\nTransposed Matrix:\n", transposed_matrix)


Transposed Matrix:
 [[1 4]
 [2 5]
 [3 6]]


## Random Number Generation

In [ ]:
random_array = np.random.rand(2, 4)  # 3x3 matrix with random values between 0 and 1
print("\nRandom Array:\n", random_array)


Random Array:
 [[0.70798661 0.66615173 0.12745068 0.50421923]
 [0.48132989 0.24998303 0.19003588 0.29320338]]


## Indexing and Slicing

In [ ]:
print("\nFirst element:", matrix[0,2])
print("\nLast three elements:", matrix[-1:,-2:])


First element: 3

Last three elements: [[5 6]]


## Statistical Operations

In [ ]:
mean_value = np.mean(matrix)
std_deviation = np.std(matrix)
median_value = np.median(matrix)

print("\nMean:", mean_value)
print("\nStandard Deviation:", std_deviation)
print("\nMedian:", median_value)


Mean: 3.5

Standard Deviation: 1.707825127659933

Median: 3.5
